### ISSUE TITLE
Accepted name not appearing in search results

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-profile#1]
From a user:

> On 17 May 2015, at 5:49 pm, Terry Annable terry.annable@avondale.edu.au wrote:
> Hi.
> Why is it that when I look up the reticulated footman moth (which is moderately common in this area) I find the name Scaptesyle dichotoma but the accepted name is given as Chirife dichotoma?. However when I look up this name there is no result for either the the binomial or the genus on its own.
> Thanks
> Terry Annable

So `Chirife dichotoma` which comes back as the accepted name for [`Scaptesyle dichotoma`](http://bie.ala.org.au/search?q=Scaptesyle+dichotoma), does not come up in the BIE search results: http://bie.ala.org.au/search?q=Chirife+dichotoma

**Comment by nickdos** [comment]
Should this be in `bie-service` instead?

**Comment by djtfmartin** [comment]
I've replied

```Thanks for getting in touch Terry.

The accepted name for Scaptesyle dichotoma is given as Chiriphe dichotoma, not Chirife dichotoma.

Search for the genus and bionomial seems to be working ok:

1) bionomial: http://bie.ala.org.au/search?q=Chiriphe+dichotoma
2) genus: http://bie.ala.org.au/search?q=Chiriphe

Thanks again

Dave Martin 
ALA```

Closing
